/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2013 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.ishan.androidpdf;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.HashMap;

import net.sf.andpdf.pdfviewer.PdfViewerActivity;

import org.appcelerator.kroll.KrollDict;
import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.titanium.TiApplication;

import android.content.Intent;
import android.os.Environment;
import android.test.UiThreadTest;

@Kroll.module(name = "Androidpdf", id = "com.ishan.androidpdf")
public class AndroidpdfModule extends KrollModule {

	// Standard Debugging variables
	private static final String TAG = "AndroidpdfModule";

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public AndroidpdfModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(TAG, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
	}

	// Methods
	@Kroll.method
	public void openPDF(@SuppressWarnings("rawtypes") HashMap hashmap)
			throws FileNotFoundException {

		KrollDict arguments = new KrollDict(hashmap);
		String fileName = (String) arguments.get("fileName");

		String packageName = getActivity().getPackageName();
		String filePath = Environment.getExternalStorageDirectory()
				.getAbsolutePath() + "/" + packageName + "/" + fileName;

		File getFile = new File(filePath);

		if (getFile.exists()) {
			openPdfIntent(getFile.getAbsolutePath());
		} else {
			throw new FileNotFoundException("The file name " + fileName
					+ " does not exists");
		}
	}

	private void openPdfIntent(String path) {
		try {
			final Intent intent = new Intent(TiApplication
					.getAppRootOrCurrentActivity().getApplicationContext(),
					pdfviewer.class);

			intent.putExtra(PdfViewerActivity.EXTRA_PDFFILENAME, path);

			TiApplication.getAppRootOrCurrentActivity().startActivity(intent);
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

}
